import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, home }) {
  return (
    <html>
      <Head>
        <title>ASTROCAT TEACHES VEX</title>
      </Head>

     <body>

        {/* <Image
      
          src="/astrocatpfp.jpeg"
          height={200}
          width={200}
          alt="astro cat"
        /> */}

      <Link href="/" >
        <Image
          src="/astrocatpfp.jpeg"
          height={200}
          width={200}
          alt="astro cat"
        />
      </Link>

        
      {children}

      

     </body>
     
     
    </html>
  )
}
